### ISSUE TITLE
UX Audit of 5 DApps

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/design#1]
**# UX Audit of 5 DApps**

Decentralized apps, DApps, are the Apps of Web3.0. They are decentralized applications that use blockchain and smart contracts as their backend. 

Status wants to help people onboard to web3.0. The more DApps are available on this new web, the higher the likelihood of people finding applications that are meaningful for them. For reference, the App store would not be interesting if it offered only 1 app and a TV network would not be as interesting if it offered only one channel. 

We want to increase the number of quality DApps by providing developers UX guidelines for good DApp design. Understanding what makes a good DApp is the first step.

## **Task**

- Conduct a UX audit of 5 DApps of your choosing (excluding Status core app).
- Use well known usability heuristics and describe positive findings and areas of improvement.
- Identify heuristics that you find are specific to a good DApp experience.

## **Deliverable**

- Overview of DApp performance on each heuristic.
- Illustration of key heuristics with screenshots 
- App store design guidelines

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 5000.00
Contract address: [0x2c20b0bfc12345da97a1b405210b56cd1c515fb3](https://etherscan.io/address/0x2c20b0bfc12345da97a1b405210b56cd1c515fb3)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: alegw
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by alescode** [comment]
Hey peeps!

I'm tackling this one for the next couple days. Did a UX audit of Peepeth and started gathering usability heuristics specific to Ðapps.

If you're curious, here's a sneak peek. I like Markdown for these kinds of written tasks, but am open to format suggestions: 
https://hackmd.io/FhfCq-rCTyKFQ_j6eyKSjw

Comments welcome!

<blockquote><img src="https://hackmd.io/favicon.png" width="48" align="right"><div><strong><a href="https://hackmd.io/FhfCq-rCTyKFQ_j6eyKSjw">UX Audit of 5 Ðapps - HackMD</a></strong></div></blockquote>

**Comment by hesterbruikman** [comment]
Great start @alegw!

Looking forward to see how Peepeth compares to some other DApps and understand if there are basic heuristics that are structurally lacking (e.g. due to ecosystem limitations) that we can shift our focus to.

 Thanks for the update!

**Comment by alescode** [comment]
Ok, just finished producing a thorough report. You can [read the whole thing here](https://hackmd.io/FhfCq-rCTyKFQ_j6eyKSjw). I offer my recommendations humbly, since I'm new to the space:

1. Acquiring ether and convincing users to spend it are the main sources of initial friction. Let's keep working on ways to abstract gas away during onboarding. Good resources to build on are [this talk on Universal Logins](https://www.youtube.com/watch?v=qF2lhJzngto), and the current implementation of [Identity Gas Relay](https://github.com/status-im/contracts/blob/73-economic-abstraction/contracts/identity/IdentityGasRelay.sol).
2. Currently, the burden of estimating fees and letting users pick a confirmation speed is on Ðapp developers. This is inefficient for developers (reinventing the wheel) and confusing for users (variety of interfaces for the same task). Let's research if web3 providers could take over this responsibility.
3. Ðapps should [follow standards for signing messages](https://eips.ethereum.org/EIPS/eip-712). If users can be certain that a transaction is being requested from a URL they trust, there'll be less of a need to prime them before every transaction – explanations could be embedded in the web3 provider's request.
4. Ðapps should be able to communicate with users that opt-in by using their Ethereum address. This would enable natively notifying the user when his transactions go through. We should converge on an [address-to-address messaging standard](https://github.com/ethereum/EIPs/issues/802), but communication should operate off-chain.
5. Making [web3 access opt-in](https://eips.ethereum.org/EIPS/eip-1102) will be key to avoid fingerprinting. We should propose a standard that web3 providers follow when requesting the user's permission to expose a wallet address.
6. web3 providers should use USD when communicating with the user, or even better, request the user's native currency. Toshi does a fantastic job here.
7. There should be a standard way to open Ðapp links in the user's preferred application. Let's research how this could be done.
8. Let's create a standard on how logging out works: should it require signing a message? should Ðapps flush cookies upon logout?

If this has been useful, I'd like to review [Bloom](https://bloom.co). They invest heavily in user experience, and we could derive more heuristics from a thorough analysis. It doesn't work on Status yet – they use Metamask-specific code and are planning to roll out native apps that also act as web3 providers. [ETHLance](https://ethlance.com/) could also be interesting, although my first impression is that the signup cost of around $10 is too high for most users.

 @hesterbruikman @jpbowen

**Comment by alescode** [comment]
Hey, any updates here?

**Comment by hesterbruikman** [comment]
Thanks for pinging @alegw ! Totally missed this while I was out on vacation. I'll walk through the report today. Thanks for preparing!

**Comment by alescode** [comment]
Is the Open Bounty app working correctly? The pull request was merged, but the 5000 SNTs haven't been transferred.

**Comment by pablanopete** [comment]
@alegw sorry for the slow response on bounty payout, could you drop your wallet address here so I can send you the bounty amount Out of Band while we wait on a dashboard fix in Status Open Bounty. 

If you don't feel comfortable putting it here in the comment could you email a ERC20 compatible wallets address to me? chris.hutchinson@status.im

**Comment by alescode** [comment]
Emailed. Thanks!

**Comment by pablanopete** [comment]
Payout sent!
