### ISSUE TITLE
Explain anonymized names

### ISSUE THREAD

**Issue by obi2020** [status-im/design#26]
### User Story
As a user, I want to know why I and others appear in chats with random 3-word names so that I understand when/where my chosen name appears and what it means (anonymous or not).

### Issue Description

Issue Type: Misunderstanding

Observed behavior: 

During onboarding the user is asked to create a display name and is told that this is the name by which "everyone" on Status will know them. In fact, unless people are connected contacts, they will see the user as an anonymized 3-word name. 

Cause: 

The reason for, and application of, the anonymized names is not explained anywhere. 

### Solution / Suggestion for improvement
[comment]: # (Summarise the solution and provide a task list on what needs to be fixed.)
Summary: 
- Add a note during onboarding while name is being created, e.g. "your contacts will see this name, everyone else will see an anonymized name..."
- Explain it in the profile during edit, or in a tooltip, or???
- First run pop-ups: first time someone uses public chat, a pop up that explains why the names look as they do
- 

### Additional Information (optional)

Status version: 0.9.25 
Operating System: Android
Device model: Pixel

**Comment by obi2020** [comment]
@lukaszfryc we chatted about this in slack and I offer that maybe this screen during onboarding was a good place to explain this. It still may be, but insights show that users often don't read or don't retail this messages I opened this issue to see if we can explore either design-oriented solutions, or placement elsewhere in the flow cc: @EugeOrtiz 

Sample updated copy:
> Your contacts will see this name and everyone else will see an anonymized name. Change display name anytime in your profile.

![onboarding-display-name](https://user-images.githubusercontent.com/3373750/43611419-0ba5e7ce-9677-11e8-8755-950524c9b741.png)

**Comment by lukaszfryc** [comment]
@obi2020 I think it's a great place to introduce the concept of anonymized names. I like the copy. 

We may also think of some design changes around messages or user profile. Let's say I'm in public chat reading messages. First thing I notice are weird names like "Drab Jumbo Curl". I may think that those are bots or something. Maybe we could indicate here that someone is your contact by adding a contact badge icon on the avatar? 

<img src="https://user-images.githubusercontent.com/7532782/43631696-39ece960-9704-11e8-99e9-820b6d47681b.png" width="200">

Here, it also would be great for user to understand (or remind him/her) that that name is anonymous name because this user has not added you to his contact list 
<img src="https://user-images.githubusercontent.com/7532782/43631574-d5b5b2d8-9703-11e8-9814-ac63d9a4b58c.png" width="200">

**Comment by denis-sharypin** [comment]
I even think maybe this feature requires a standalone screen during onboarding? This feauture is based on our values and we could mention there something like "Status is anonymous by default" and outline the information about these names and that anyone can check your wallet address (and balance) if you add them as a contact.

**Comment by lukaszfryc** [comment]
@denis-sharypin @obi2020 there is UXR session in the upcoming weeks. Maybe it's worth testing 2 versions of the mockup to see which one users understand? One with only copy and the other with standalone onboarding screen? cc @hesterbruikman

**Comment by EugeOrtiz** [comment]
Hi all! We were exploring other moments in which we could explain/show the value of anonymous names. The main idea is to explain it **in context**. I think onboarding is not a good context to do it because during onboarding:

a) We have bigger things to communicate (how the app helps achieve our user's goals, welcome and excite users)
b) The user is not yet familiar with the app’s UI or the fact that there are random names, or ready to learn about it
a) The user may be eager to try the app without reading an instruction manual

So, we thought that the best moment to explain what these random names are is when the user actually encounters them, during the chat experience.
Here is a rough mockup, copy and design are not final: 

![random names](https://user-images.githubusercontent.com/37297779/43802409-16ae3c72-9a6c-11e8-8155-11b8cd7faaf2.png)

Happy to explore and test other options that can follow this line of thought! Let me know what you think.
@obi2020 @denis-sharypin @lukaszfryc

**Comment by lukaszfryc** [comment]
@EugeOrtiz I like this in-context explanations. Btw, I imagine that pressing "Got it" will hide the button.

@hesterbruikman I think we should test it in the UXR session.

**Comment by hesterbruikman** [comment]
Thanks for pinging @lukaszfryc 


I have a lot of thoughts on the topic below. I totally support testing the feature and would love to take it along in a next round (likely early October) on Inviting friends (including ENS and universal links). Until then, I honestly think we have some work to do to find an optimal flow to test and compare with what we have now. 

### Name sharing logic
There is something strange about the naming structure all together. _@EugeOrtiz I recall we discussed this in Amsterdam, but my memory is foggy._

The current logic is that I only see someone's public name when after I **received** a contact request **ánd** **added** them as a contact. I would actually imagine that when I'm the person sending out the invite I would want recipients to see my public name, so that they know that it's me. In return it makes sense that I only get to see their public name after they added me back. 

To complicate things **Received**  does have the, IMO, edge case of people wanting to publically share their anonymous name:S or for whatever reason send an invite anonymously. I would argue that those who want to remain anonymous at all times would simply keep their random name. Which could mean, bringing this back into Onboarding. Random names in onboarding caused confusion in 1 design we tested; doesn't mean it can't be done.

### Design-oriented solutions

- @lukaszfryc I really like the thought of indicator icons next to a name. Could be an indicator of:
anonymous/random vs public name (1 variable, 2 states)
contact vs no contact (1 variable, 2 states)
We could choose to indicate either states or both for each variable. 
- @denis-sharypin great idea to include a warning on that connecting with a public name entails sharing your wallet address.
- @obi2020  You describe a good guide of locations to inform: Onboarding, Profile, Chat creation. Although I agree with @EugeOrtiz that Onboarding is not the place to go int details, the naming should signal that their are different naming types. 
- @EugeOrtiz really like to drawer pattern for 'in-app onboarding'. Really helps to think out of the framework of onboarding being a first time use flow only.

### Labeling
- We use **Display name** now, which is not accurate in all cases. @obi2020 Would also love to hear your thoughts on how we should call these name variation in the app, e.g. Display name, Anonymous name, Random name, Public name, Private name.

**Comment by lukaszfryc** [comment]
> I would actually imagine that when I'm the person sending out the invite I would want recipients to see my public name, so that they know that it's me. In return it makes sense that I only get to see their public name after they added me back.

This is exactly how it works right now. Recipients see your name and avatar and you get to see theirs once they add you to the contact list.

> anyone can check your wallet address (and balance) if you add them as a contact.

@denis-sharypin @hesterbruikman I believe you can check someone's balance without being on their contact list. When I go to public chat, click on some user's avatar, start a conversation with her, add her as contact, then I can go to wallet and send transaction to her. So, I know here wallet address & and I can check the balance. Please correct me if I'm wrong.

**Comment by hesterbruikman** [comment]
Sorry I've left this for so long. This is still the case and should be fixed. We'll start a design project shortly that can address this. So intertwined that I don't see a quick fix. As in theory it should be possible to send someone that is not a connection a transaction.
